version: "3.9"

services:
  # Auth service (ASP.NET)
  auth:
    build:
      context: ./AuthService      # <-- folder with your auth project + Dockerfile
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "5027:5027"                # host:container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5027
      - ConnectionStrings__Default=Data Source=/app/App_Data/app.db
    volumes:
      - ./AuthService/App_Data:/app/App_Data   # persist sqlite (or other files) on host
    

  # Messaging service (ASP.NET or Node; here assumed ASP.NET)
  messenger:
    build:
      context: ./MessageService  # <-- folder with your messaging project + Dockerfile
      dockerfile: Dockerfile
    container_name: messenger
    ports:
      - "5091:5091"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5091
      - ConnectionStrings__Default=Data Source=/app/App_Data/app.db
    volumes:
      - ./MessageService/App_Data:/app/App_Data
    depends_on:
      - auth
   

  # Frontend (Vite -> production served by nginx)
  web-client:
    build:
      context: ./messanger-web        # <-- folder with your Vite project + Dockerfile
      dockerfile: Dockerfile
    container_name: web-client
    ports:
      - "5173:80"                    # host:container (nginx serves on container port 80)
    environment:
      - NODE_ENV=production
   
