version: "3.9"

services:
  # Auth service (ASP.NET)
  auth:
    build:
      context: ./AuthService      # <-- folder with your auth project + Dockerfile
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "5027:5027"                # host:container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5027
      - ConnectionStrings__DefaultConnection=Data Source=/app/App_Data/auth.db
    volumes:
      - ./data/auth:/app/App_Data   # persist sqlite (or other files) on host
    restart: unless-stopped

  # Messaging service (ASP.NET or Node; here assumed ASP.NET)
  messenger:
    build:
      context: ./MessageService  # <-- folder with your messaging project + Dockerfile
      dockerfile: Dockerfile
    container_name: messenger
    ports:
      - "5091:5091"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5091
      - ConnectionStrings__DefaultConnection=Data Source=/app/App_Data/msg.db
    volumes:
      - ./data/messaging:/app/App_Data
    depends_on:
      - auth
    restart: unless-stopped

  # Frontend (Vite -> production served by nginx)
  client:
    build:
      context: ./messanger-web        # <-- folder with your Vite project + Dockerfile
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:80"                    # host:container (nginx serves on container port 80)
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://auth:5027  # use service name for internal network DNS
    restart: unless-stopped
