version: "3.9"

services:
  # Production container (builds using Dockerfile and serves with nginx)
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: messenger_web    
    container_name: messenger_web
    ports:
      - "5173:80"       # host:container -> visit http://localhost:5173
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development container (hot reload). Use: `docker-compose up --build client-dev`
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: messenger_web_dev
    container_name: messenger_web_dev
    ports:
      - "5173:5173"     # Vite dev server
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app         # mount code for live edit
      - /app/node_modules
    tty: true
    stdin_open: true
