version: '3.9'
services:
  web:
    build: .
    container_name: auth_service
    ports:
          - "5027:5027" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="http://+:5027"
    volumes:
      - ./App_Data:/app/App_Data
    command: dotnet run --urls "http://+:5027"
